on:
  release:
    types: [created]

name: Deploy to Amazon S3

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    
    - name: Node Setup
      uses: actions/setup-node@v1
      with:
        node-version: 12
    
    - name: npm install
      run: npm install
      
    - name: npm build
      run: npm run build
      
    - name: copy files to s3
      run: aws s3 sync ./build s3://react-to-s3-sample

    - name: Invalidate cache
      run: |
          aws cloudfront create-invalidation \
            --distribution-id E2OQJQKJ0BM4TM \
            --paths "/*"
   
